language: node_js
dist: bionic

before_script:
  - npm run db:migrate

env:
  - dbUser=postgres dbPassword= dbName=postgres

node_js:
  - 10

addons:
  postgresql: "10"

matrix:
  include:
    - node_js: "10"
      addons:
        postgresql: "10"

install:
  - npm install

cache: npm

script:
  - npm run lint
  - npm run test
  - npm run build
