language: node_js
dist: bionic

before_script:
  - npm run db:migrate

env:
  - dbUser=postgres dbPassword= dbName=postgres

node_js:
  - 10

addons:
  postgresql: "10"

matrix:
  include:
    - node_js: "10"
      addons:
        postgresql: "10"

install:
  - npm ci
  - cd client && npm ci && cd ../

cache: npm

script:
  - npm run build && cd client && npm run build && cd ../
  - npm run lint
  - npm run test
