version: 2
jobs:
  build:
    branches:
      only:
        - /.*/
    docker:
      - image: circleci/node:10.17
        environment:
          dbUser: postgres
          dbName: postgres
          dbPassword:
      - image: circleci/postgres:latest-postgis
    working_directory: ~/todo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
          - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: cd client && npm i && cd ../
      - run: npm run build && cd client && npm run build && cd ../
      - run: npm run lint
      - run: npm run test
