name: Node CI

on: [push]

jobs:
  build:
    name: main

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:10
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports: ["5432:5432"]

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install and build
      env:
        CI: true
        dbUser: postgres
        dbName: postgres
        dbPassword: postgres
      run: |
        npm ci
        npm run build
        npm run db:migrate
        cd client
        npm ci
        npm run build
    - name: lint test
      env:
        CI: true
        dbUser: postgres
        dbName: postgres
        dbPassword: postgres
      run: |
        npm run lint
        npm test
